//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forums
    {
        public System.Guid ForumID { get; set; }
        public string ForumName { get; set; }
        public string ForumDescription { get; set; }
        public System.Guid CreateUserID { get; set; }
        public string CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Active { get; set; }
    }
}
