//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Threads
    {
        public System.Guid ThreadID { get; set; }
        public string Subject { get; set; }
        public int VoicesCount { get; set; }
        public int RepliesCount { get; set; }
        public string Description { get; set; }
        public System.Guid ThreadStatusID { get; set; }
        public System.Guid ForumID { get; set; }
        public System.Guid CreatedUserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
